# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.6.0-138-g84e186b
_src_path: https://github.com/usnistgov/cookiecutter-nist-python.git
command_line_interface: argparse
conda_channel: wpk-nist
email: wpk@nist.gov
full_name: William P. Krekelberg
github_username: wpk-nist-gov
project_name: typecheck-runner
project_short_description: Unified api to multiple typecheckers
project_slug: typecheck_runner
pypi_username: wpk-nist
sphinx_theme: sphinx_book_theme
sphinx_use_autodocsumm: true
year: '2025'
