- id: typecheck-runner
  name: typecheck-runner
  description: Run type checkers
  entry: python -m typecheck_runner
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
