name: Build and verify package

on:
  workflow_call:
    inputs:
      extra-checks:
        description: "Run additional checks on the build"
        required: false
        type: boolean
        default: false
      extra-python-versions:
        description:
          "extra python versions to include passes as comma separated values"
        required: false
        type: string
        default: "[]"
      smoke-test:
        description: "Run smoke tests on distribution"
        required: false
        type: boolean
        default: false
      set-python-outputs:
        description: "If true, set outputs"
        required: false
        type: boolean
        default: false
      attest-build-provenance-github:
        description:
          "Parameter to pass to hynek/build-and-inspect-python-package"
        required: false
        type: boolean
        default: false
    outputs:
      default-python-version:
        description: "python version read from .python-version file"
        value: ${{ jobs.build.outputs.default-python-version }}
      min-python-version:
        description: "min python version read from pyproject.toml"
        value: ${{ jobs.build.outputs.min-python-version }}
      max-python-version:
        description: "max python version read from pyproject.toml"
        value: ${{ jobs.build.outputs.max-python-version }}
      minmax-python-versions:
        description:
          "min/max python versions from pyproject.toml and extra-python-versions"
        value: ${{ jobs.build.outputs.minmax-python-versions }}
      minmax-default-python-versions:
        description: "min/max, default, and extra-python-versions"
        value: ${{ jobs.build.outputs.minmax-default-python-versions }}
      all-python-versions:
        description:
          "all python versions from pyproject.toml and extrta_python_versions"
        value: ${{ jobs.build.outputs.all-python-version }}

permissions: {}

jobs:
  build:
    name: Build & verify package
    runs-on: ubuntu-latest
    outputs:
      default-python-version:
        ${{ steps.versions.outputs.default_python_version }}
      min-python-version: ${{ steps.versions.outputs.min_python_version }}
      max-python-version: ${{ steps.versions.outputs.max_python_version }}
      minmax-python-versions:
        ${{ steps.versions.outputs.minmax_python_versions }}
      minmax-default-python-versions:
        ${{ steps.versions.outputs.minmax_default_python_versions }}
      all-python-version: ${{ steps.versions.outputs.all_python_versions }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0
        id: baipp
        with:
          attest-build-provenance-github:
            ${{ format('{0}', inputs.attest-build-provenance-github) }}

      - name: Set python version parameters
        id: versions
        if: inputs.set-python-outputs
        shell: python
        env:
          python_classifiers:
            ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}
          extra-python-versions: ${{ inputs.extra-python-versions }}

        run: |
          import os
          import json
          from pathlib import Path

          default_python_version = Path(".python-version").read_text().strip()
          python_versions = json.loads(os.getenv("python_classifiers"))
          extra-python-versions = [_.strip() for _ in os.getenv("extra_python_versions").split(",")]

          min_python_version = python_versions[0]
          max_python_version = python_versions[-1]
          minmax_python_versions = [min_python_version, max_python_version, *extra-python-versions]
          minmax_default_python_versions = list({*minmax_python_versions, default_python_version})
          all_python_versions = list({*python_versions, *extra-python-versions})

          print("{default_python_version=:s}")
          print("{min_python_version=:s})
          print("{max_python_version=:s})
          print("{minmax_python_versions=}")
          print("{minmax_default_python_versions=}")
          print("{all_python_version=}")


          with open(os.getenv("GITHUB_OUTPUT"), "a") as f:
            f.write(f"{default_python_version=:s}\n")
            f.write(f"{min_python_version=:s}\n")
            f.write(f"{max_python_version=:s}\n")
            f.write(f"minmax_python_versions={json.dumps(minmax_python_versions)}\n")
            f.write(f"minmax_default_python_versions={json.dumps(minmax_default_python_versions)}\n")
            f.write(f"all_python_versions={json.dumps(all_python_versions)}\n")

      - name: Check no changelog fragments
        if: inputs.extra-checks
        run: |
          shopt -s nullglob
          for _ in changelog.d/*.md ; do
              echo "Error: changelog snippets found"
              exit 1
          done
          echo "Success: no changelog snippets"
        shell: bash

      - name: Check version
        if: inputs.extra-checks
        env:
          tag_name: ${{ github.event.release.tag_name }}
          DIST: "/tmp/baipp/dist"
        run: >-
          uv run --script tools/check_dist_version.py --version "$tag_name" --
          "${DIST}"/*.whl "${DIST}"/*.tar.gz

  smoke-test:
    name: Smoke test package
    if: inputs.smoke-test
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: Packages
          path: dist
      - uses: ./.github/actions/setup-cached-uv-and-python
        with:
          python-version-file: ".python-version"
      - name: Smoke test wheel
        run:
          uv run --isolated --no-project --with dist/*.whl tests/test_smoke.py
      - name: Smoke test source
        run:
          uv run --isolated --no-project --with dist/*.tar.gz
          tests/test_smoke.py
